### ISSUE TITLE
NameError: name 'spark' is not defined

### ISSUE THREAD

**Issue by Gauravs41** [IBM/elasticsearch-spark-recommender#43] opened 2018-09-07 11:05 UTC
#first import a few utility methods that we'll use later on
from IPython.display import Image, HTML, display
 #check PySpark is running
spark

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-456c22950c2a> in <module>()
      2 from IPython.display import Image, HTML, display
      3 # check PySpark is running
----> 4 spark

NameError: name 'spark' is not defined

I running this file in Anaconda Jupyter. How can i solve this?

**Comment by loafyloaf** [comment] 2019-03-29 22:53
duplicate of #34

**Closed by loafyloaf** 2019-03-29 22:53 UTC
